services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: node_app
    depends_on:
      - db
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASS=pass
      - DB_NAME=inventory
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev

volumes:
  db_data:
